---

- name: Ensure source dir exists
  file: 
    path: "{{ src_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Clone repo to the source dir
  git:
    repo: 'https://github.com/Netflix/security_monkey.git'
    dest: "{{ src_dir }}"

- name: Run the secmon_setup
  shell: 
    args: secmon_setup.sh

- name: Get static files
  unarchive: 
    src: "{{ static_url }}"
    dest: "{{ src_dir }}/security_monkey/"
    group: www-data

- name: Update config files
  lineinfile: 
    path: "{{ src_dir }}/security_monkey/env-config/config.py"
    regexp: '^SQLALCHEMY_DATABASE_URI ='
    line: "SQLALCHEMY_DATABASE_URI = 'postgresql://{{db.user}}:{{ db.password }}@localhost:5432/secmonkey'"
  tags:
    - sql_uri

- name: Update config files
  lineinfile: 
    path: "{{ src_dir }}/security_monkey/env-config/config.py"
    regexp: '^FQDN ='
    line: "FQDN = '{{ fqdn }}'"
  tags:
    - fqdn

- name: Update config files
  lineinfile: 
    path: "{{ src_dir }}/security_monkey/env-config/config.py"
    regexp: '^MAIL_DEFAULT_SENDER ='
    line: "MAIL_DEFAULT_SENDER = '{{ mail_sender }}'"
  tags:
    - mail_sender

